### ISSUE TITLE
Getting teleportet back to the pole

### ISSUE THREAD

**Issue by jajajafeti** [Seth0067/tothebatpoles#13]
Hi, as you can see there is something wrong and I managed to recreate it. In the video you can see me doing two attempts, the first one it was fine but in the second it worked (the bug), so its not always 100% of the time. But If you stand on the middle of the block and look at the pole you get instantly attached (which is kinda confusing to me but not important for the bug I only used it in the video). So I jump (important) from the middle of the block and look at the pole, now it constantly attaches and detaches me from the pole becaus of the structer I build around the pole (important to recreate it). If I now press shift to detach and walk away and pres shift again it teleports me to the pole. It only gets fixed if I place another block around the pole (see video).

I play on the Version "_AdPoles-1.16.4-5.0.3.0-build.0027_" with "_ForgeEndertech-1.16.4-7.0.8.0-build.0028_"

I suggest (not only becaus of the bug, but also becaus it would make it smoother) to have a cooldown option in the config file, so you can tune the time which has to pass between detaching and attaching to a pole.

https://user-images.githubusercontent.com/61298096/106611528-6034a880-6568-11eb-8c0c-831d0911e9c8.mp4

**Comment by EnderLanky** [comment]
Finally fixed all these issues, including the teleportation bug, in [the recent update](https://www.curseforge.com/minecraft/mc-mods/to-the-bat-poles/files/3362201). Thank you for the report!
