### ISSUE TITLE
Getting sucked into the pole

### ISSUE THREAD

**Issue by mikaela01a** [Seth0067/tothebatpoles#14]
I am aware that there is already another issue opened with this. However i am on a different version of the mod: 
AdPoles - 1.16.4-5.0.4.0-build.0095
ForgeEndertech - 1.16.4-7.1.00
forge - 1.16.5-36.1.0

If there is a block placed directly next to a pole and you walk past within a half block distance, you automatically get sucked onto the pole. I found the only way to avoid this is to crouch past the pole. 

On a related note, you do suffocate in the walls and do not dismount from the pole unless you crouch. i could not spin out of the wall even though there was no other blocks on the other side of the pole. 
This does not apply to the fences. This only happens with the added pole items.

**Comment by EnderLanky** [comment]
All these issues should be fixed in [the recent update](https://www.curseforge.com/minecraft/mc-mods/to-the-bat-poles/files/3362201). Thanks for reporting!
